import { Column, CreateDateColumn, Entity, Index, PrimaryGeneratedColumn, Unique, UpdateDateColumn } from 'typeorm';

/**
 * One indexed, cross-domain search result. This table is a DERIVED STORE —
 * search-service never originates this data. Every row here is a projection
 * built entirely from `*.published` / `*.updated` / `*.deleted` domain events
 * consumed off every content service's exchange (see
 * infrastructure/messaging/event-consumer.ts and event-mapper.ts). It is
 * always safe to truncate this table and rebuild it by replaying events —
 * there is deliberately no write/ingest REST endpoint (see docs/erd.md).
 *
 * `searchVector` is a generated tsvector column (title weighted 'A',
 * description weighted 'B') created via raw SQL in the initial migration —
 * TypeORM doesn't model generated/tsvector columns natively, so it's
 * declared here only for typing/reads, never written to by the app.
 */
@Entity({ name: 'search_documents' })
@Unique('uq_search_documents_entity', ['entityType', 'entityId'])
export class SearchDocument {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** e.g. 'journal_article', 'ebook', 'wiki_article', 'repository_item', 'researcher_profile'. Kept as an indexed varchar (not an enum) since new content types arrive without a migration. */
  @Index()
  @Column({ name: 'entity_type', type: 'varchar', length: 100 })
  entityType!: string;

  /** The id of the record in the owning content service — NOT this table's own pk. */
  @Column({ name: 'entity_id', type: 'varchar', length: 255 })
  entityId!: string;

  @Column({ type: 'text' })
  title!: string;

  @Column({ type: 'text', nullable: true })
  description!: string | null;

  @Column({ type: 'text', array: true, nullable: true })
  tags!: string[] | null;

  /** Canonical link/path for the frontend to route to. */
  @Column({ type: 'text', nullable: true })
  url!: string | null;

  /** Which service produced this document, e.g. 'journal-service'. */
  @Index()
  @Column({ name: 'source_service', type: 'varchar', length: 100 })
  sourceService!: string;

  @Column({ name: 'published_at', type: 'timestamptz', nullable: true })
  publishedAt!: Date | null;

  @Column({ type: 'jsonb', nullable: true })
  metadata!: Record<string, unknown> | null;

  /** Read-only in application code; generated by Postgres from title + description. See the initial migration. */
  @Column({ name: 'search_vector', type: 'tsvector', select: false, insert: false, update: false })
  searchVector!: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;
}
